# Regresión lineal en Python con Scikit-learn

### Regresión lineal y la selección de rasgos

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.svm import SVR  #super vector maching (para modelo lineal)

In [3]:
data = pd.read_csv(r'F:\BD\GitHub\mlearningcourse\datasets\ads\Advertising.csv')

In [5]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
# Selección de Variables predictivas
feature_cols =['TV','Radio','Newspaper']

In [9]:
x = data[feature_cols]  # Variables candidatas a predictoras
y = data['Sales']   # Variable a predecir

In [28]:
#Paquetes de la libreria de SciKit Learn (Para modelo lineal)

estimator = SVR (kernel = 'linear')
selector = RFE (estimator, 2, step = 1)   #<--- El 2 representa que únicamente deseamos dos variables predictoras
selector = selector.fit(x,y)

In [27]:
#De las variables candidatas, ¿cuales son las mejores?
selector.support_  #(elimina 'NewsPaper')

array([False,  True, False])

In [17]:
# Otra manera de conocer las variables no discriminadas, son las que valen 1
selector.ranking_

array([1, 1, 2])

#### Otra manera de hacer regresión lineal con SKL

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
X_pred = x[['TV','Radio']] #Variables predictoras

In [20]:
lm = LinearRegression()
lm.fit(X_pred, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
#Dónde corta el intercepto
lm.intercept_

2.9210999124051362

In [22]:
#Coeficientes
lm.coef_

array([0.04575482, 0.18799423])

In [23]:
#R2 ajustado
lm.score(X_pred, y)

0.8971942610828956

## Regresiones con variables categóricas