# El método k-means

* Métodos aleatorios entre 0 y 1

In [1]:
import numpy as np

In [3]:
# Genera 90 números aleatorios y se acomodan en 3 columnas de 30 filas cada una
data = np.random.random(90).reshape(30,3)
data

array([[0.41858183, 0.80290495, 0.93418432],
       [0.42616242, 0.12080049, 0.72897783],
       [0.31635854, 0.05716505, 0.41579407],
       [0.09147284, 0.26316267, 0.90940901],
       [0.60417121, 0.44099199, 0.79925853],
       [0.72319142, 0.32906845, 0.33617586],
       [0.15401725, 0.62825432, 0.37907774],
       [0.65404394, 0.4703305 , 0.83253464],
       [0.81680297, 0.46323306, 0.33765873],
       [0.47211939, 0.71473618, 0.86543244],
       [0.28602987, 0.70841004, 0.60390479],
       [0.87611539, 0.51606431, 0.17090866],
       [0.54232362, 0.35371189, 0.45174799],
       [0.40932824, 0.30420663, 0.92965329],
       [0.40865829, 0.16895608, 0.56388678],
       [0.81030685, 0.21663085, 0.44621135],
       [0.41448224, 0.66796737, 0.23950158],
       [0.14699357, 0.65693375, 0.9915201 ],
       [0.957561  , 0.91740827, 0.97977496],
       [0.53263769, 0.15999628, 0.12310307],
       [0.65306678, 0.01154278, 0.24795584],
       [0.12670402, 0.3146576 , 0.17856108],
       [0.

In [7]:
# Seleccionar de manera aleatoria 2 observaciones, que serán los centroides

cl = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[cl], data[c2]])   # Selecciona dos filas al azar
clust_centers

array([[0.0918693 , 0.05756703, 0.51416589],
       [0.957561  , 0.91740827, 0.97977496]])

In [8]:
from scipy.cluster.vq import vq

In [9]:
vq(data, clust_centers)

(array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 1]),
 array([0.55289064, 0.40236119, 0.24509712, 0.44551862, 0.62003467,
        0.70990217, 0.5897416 , 0.56007219, 0.79900012, 0.53833423,
        0.68508979, 0.90662841, 0.54268487, 0.57813584, 0.33946274,
        0.73896661, 0.74303982, 0.76820973, 0.        , 0.59807914,
        0.62283918, 0.42419289, 0.4421341 , 0.        , 0.84832082,
        0.79703277, 0.63623868, 0.65309262, 0.53229826, 0.69565835]))

* Primer array dice a que clúster pertenece cada una de las observaciones
* Cada uno de los valores, muestra las distancias de cada observación en relación  los clústers seleccionados

In [10]:
from scipy.cluster.vq import kmeans

In [12]:
kmeans(data, clust_centers)  # Para visualizar baricentros

(array([[0.46737207, 0.3089641 , 0.34408309],
        [0.47518716, 0.59634975, 0.80563319]]), 0.3614778698929921)