# Analisis de componentes principales

* Estandarizar los datos (para cada una de las m observaciones)
* Obtener los vectores y valores propioes a partir de la matriz de covarianzas o de correlaciones o incluso la técnica de singular vector decomposition.

* Ordenar los valores propios en orden descendente y quedarnos con los *p* que se correspondan a los *p* mayores y así el número de variables del dataset (p<m)
* Construir la matríz de proyección W a partir de los P vectores propios
* Transformar el dataset original X a través de W para así obtener datos en el subespacio dimensional de dimensión *p* que será Y.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('F:/BD/GitHub/mlearningcourse/datasets/iris/iris.csv')
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [11]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [5]:
tls.set_credentials_file(username='tom.zg', api_key='dt0WJIBhUQ4vA6rpAh52')

In [12]:
traces = []
legend = {0:True, 1:True, 2:True, 3:True}

colors = {'setosa': 'rgb(255,127,20)',
         'versicolor': 'rgb(31, 220, 120)',
         'virginica': 'rgb(44, 50, 180)'}

for col in range(4): 
    for key in colors:
        traces.append(Histogram(x=X[y==key, col], opacity = 0.7, 
                                xaxis="x%s"%(col+1), marker=Marker(color=colors[key]),
                               name = key, showlegend=legend[col]))
        
    legend = {0:False, 1:False, 2:False, 3:False}
        
data = Data(traces)
layout = Layout(barmode="overlay", 
                xaxis=XAxis(domain=[0,0.25], title="Long. Sépalos (cm)"),
                xaxis2=XAxis(domain=[0.3, 0.5], title = "Anch. Sépalos (cm)"),
                xaxis3=XAxis(domain = [0.55, 0.75], title = "Long. Pétalos (cm)"),
                xaxis4=XAxis(domain=[0.8,1.0], title = "Anch. Pétalos (cm)"),
                yaxis=YAxis(title="Número de ejemplares"),
                title="Distribución de los rasgos de las diferentes flores Iris")

fig = Figure(data = data, layout = layout)
py.iplot(fig)

C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:426: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_dep

In [7]:

from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [8]:
traces = []
legend = {0:True, 1:True, 2:True, 3:True}

colors = {'setosa': 'rgb(255,127,20)',
         'versicolor': 'rgb(31, 220, 120)',
         'virginica': 'rgb(44, 50, 180)'}

for col in range(4): 
    for key in colors:
        traces.append(Histogram(x=X_std[y==key, col], opacity = 0.7, 
                                xaxis="x%s"%(col+1), marker=Marker(color=colors[key]),
                               name = key, showlegend=legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}
        
data = Data(traces)
layout = Layout(barmode="overlay", 
                xaxis=XAxis(domain=[0,0.25], title="Long. Sépalos (cm)"),
                xaxis2=XAxis(domain=[0.3, 0.5], title = "Anch. Sépalos (cm)"),
                xaxis3=XAxis(domain = [0.55, 0.75], title = "Long. Pétalos (cm)"),
                xaxis4=XAxis(domain=[0.8,1.0], title = "Anch. Pétalos (cm)"),
                yaxis=YAxis(title="Número de ejemplares"),
                title="Distribución de los rasgos de las diferentes flores Iris")

fig = Figure(data = data, layout = layout)
py.iplot(fig)

C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:426: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.layout.scene.XAxis


C:\Users\TOM.ZG\Anaconda3\lib\site-packages\plotly\graph_objs\_dep

### Calculamos la descomposición de valores y vectores propios

In [14]:
from IPython.display import display, Math, Latex

In [16]:
display(Math(r'\sigma_(jk)=\frac{1}{n-1}\sum_{i=1}^m(x_{ij}-\overline{x_j})(x_{ik}-\overline{x_k})'))

<IPython.core.display.Math object>

In [17]:
# Fórmula de la matriz de covarianza
display(Math(r'\Sigma = \frac{1}{n-1}((X-\overline{X})^T(X-\overline{x}))'))

<IPython.core.display.Math object>

In [18]:
display(Math(r'\overline{x}= \sum_{i=1}^n x_i \in \mathbb R^m'))

<IPython.core.display.Math object>

In [19]:
import numpy as np

In [24]:
# Vector de medias
mean_vect = np.mean(X_std, axis = 0)
mean_vect

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [29]:
# Matriz de covarianza
cov_matrix = (X_std - mean_vect).T.dot((X_std - mean_vect))/(X_std.shape[0]-1)
print('La matriz de covarianzas es :\n%s'% cov_matrix)

La matriz de covarianzas es :
[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]


In [30]:
np.cov(X_std.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [33]:
eig_vals, eig_vectors = np.linalg.eig(cov_matrix)
print('Valores propios \n', eig_vals)
print('Vectores propios \n', eig_vectors)

Valores propios 
 [2.93808505 0.9201649  0.14774182 0.02085386]
Vectores propios 
 [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]
